### PR TITLE
Parse more than the first 15 Threads

### PR DESCRIPTION
**Pull request by Bitti09**
4chan json response hase more  threads.
old code stoped after 1. page  part.

---
This change is [Reviewable](https://reviewable.io/reviews/blackdev1l/vuechan/1)

### CODE REVIEW

**Comment by blackdev1l** [comment]
First of all, thanks for the contribution, didn't know there was somebody useing this ^^ 

```
 ERROR  Failed to compile with 1 errors                                                          18:09:52

 error  in ./src/components/Catalog.vue


  ✘  http://eslint.org/docs/rules/arrow-spacing  Missing space after =>                          
  /home/cristian/dev/vuechan/src/components/Catalog.vue:37:33
            f.threads.forEach(e =>{
                                   ^

  ✘  http://eslint.org/docs/rules/indent         Expected indentation of 12 spaces but found 10  
  /home/cristian/dev/vuechan/src/components/Catalog.vue:38:11
            this.threads.push({
             ^


```

I'm sorry but you need to make it at least run without error, i can't merge if it doesn't run with the standard command

**Comment by Bitti09** [comment]
:D 
lint errors should be fixed now.
i did a new try based on vuetifyjs to play around with vue [here](https://github.com/Bitti09/vue-chan).

**Comment by blackdev1l** [comment]
```
 ERROR  Failed to compile with 1 errors                                                          17:02:26

 error  in ./src/components/Catalog.vue


  ✘  http://eslint.org/docs/rules/indent  Expected indentation of 14 spaces but found 12  
  /home/cristian/dev/vuechan/src/components/Catalog.vue:39:13
              id: e.no,
               ^

  ✘  http://eslint.org/docs/rules/indent  Expected indentation of 14 spaces but found 12  
  /home/cristian/dev/vuechan/src/components/Catalog.vue:40:13
              description: e.com.substr(0, 150),
               ^

  ✘  http://eslint.org/docs/rules/indent  Expected indentation of 14 spaces but found 12  
  /home/cristian/dev/vuechan/src/components/Catalog.vue:41:13
              img: e.tim + e.ext,
               ^

  ✘  http://eslint.org/docs/rules/indent  Expected indentation of 14 spaces but found 12  
  /home/cristian/dev/vuechan/src/components/Catalog.vue:42:13
              replies: e.replies
               ^


``` 
I dunno if it's just me or you get this error too. Let me know if you are not having the compile (duh) error, i'm curious if you are using a different eslint config or such

**Comment by Bitti09** [comment]
i'm currently not using any eslint and i don't know if vuetifyjs has  it enabled in webpack template(which i'm using).

**Comment by blackdev1l** [comment]
run `npm run dev` and fix the linting errors, otherwise you can close the pr, i can't merge at this state, sorry

**Pull request closed without merging**
